/**
 * Granular permissions for SuperAdmin staff management
 */

export enum PermissionCategory {
  USERS = 'users',
  PATIENTS = 'patients',
  PROVIDERS = 'providers',
  ORGANIZATIONS = 'organizations',
  DEVICES = 'devices',
  VITALS = 'vitals',
  BILLING = 'billing',
  CLAIMS = 'claims',
  REPORTS = 'reports',
  ANALYTICS = 'analytics',
  SETTINGS = 'settings',
  AUDIT = 'audit',
  COMPLIANCE = 'compliance',
  INTEGRATIONS = 'integrations',
  STAFF = 'staff',
  API_KEYS = 'api_keys',
  NOTIFICATIONS = 'notifications',
}

export enum PermissionAction {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  EXPORT = 'export',
  IMPORT = 'import',
  APPROVE = 'approve',
  REJECT = 'reject',
  ASSIGN = 'assign',
  REVOKE = 'revoke',
  MANAGE = 'manage',
}

export const Permission = {
  USERS_CREATE: 'users:create',
  USERS_READ: 'users:read',
  USERS_UPDATE: 'users:update',
  USERS_DELETE: 'users:delete',
  USERS_EXPORT: 'users:export',
  USERS_APPROVE: 'users:approve',
  USERS_SUSPEND: 'users:suspend',
  PATIENTS_CREATE: 'patients:create',
  PATIENTS_READ: 'patients:read',
  PATIENTS_UPDATE: 'patients:update',
  PATIENTS_DELETE: 'patients:delete',
  PATIENTS_EXPORT: 'patients:export',
  PATIENTS_ASSIGN: 'patients:assign',
  PATIENTS_ENROLL: 'patients:enroll',
  PROVIDERS_CREATE: 'providers:create',
  PROVIDERS_READ: 'providers:read',
  PROVIDERS_UPDATE: 'providers:update',
  PROVIDERS_DELETE: 'providers:delete',
  PROVIDERS_ASSIGN: 'providers:assign',
  ORGANIZATIONS_CREATE: 'organizations:create',
  ORGANIZATIONS_READ: 'organizations:read',
  ORGANIZATIONS_UPDATE: 'organizations:update',
  ORGANIZATIONS_DELETE: 'organizations:delete',
  ORGANIZATIONS_MANAGE: 'organizations:manage',
  DEVICES_CREATE: 'devices:create',
  DEVICES_READ: 'devices:read',
  DEVICES_UPDATE: 'devices:update',
  DEVICES_DELETE: 'devices:delete',
  DEVICES_ASSIGN: 'devices:assign',
  DEVICES_ORDER: 'devices:order',
  DEVICES_SYNC: 'devices:sync',
  VITALS_READ: 'vitals:read',
  VITALS_UPDATE: 'vitals:update',
  VITALS_DELETE: 'vitals:delete',
  VITALS_EXPORT: 'vitals:export',
  BILLING_READ: 'billing:read',
  BILLING_CREATE: 'billing:create',
  BILLING_UPDATE: 'billing:update',
  BILLING_DELETE: 'billing:delete',
  BILLING_EXPORT: 'billing:export',
  BILLING_APPROVE: 'billing:approve',
  CLAIMS_READ: 'claims:read',
  CLAIMS_CREATE: 'claims:create',
  CLAIMS_UPDATE: 'claims:update',
  CLAIMS_DELETE: 'claims:delete',
  CLAIMS_SUBMIT: 'claims:submit',
  CLAIMS_APPROVE: 'claims:approve',
  REPORTS_READ: 'reports:read',
  REPORTS_CREATE: 'reports:create',
  REPORTS_EXPORT: 'reports:export',
  REPORTS_SCHEDULE: 'reports:schedule',
  ANALYTICS_READ: 'analytics:read',
  ANALYTICS_EXPORT: 'analytics:export',
  ANALYTICS_ADVANCED: 'analytics:advanced',
  SETTINGS_READ: 'settings:read',
  SETTINGS_UPDATE: 'settings:update',
  SETTINGS_MANAGE: 'settings:manage',
  AUDIT_READ: 'audit:read',
  AUDIT_EXPORT: 'audit:export',
  COMPLIANCE_READ: 'compliance:read',
  COMPLIANCE_MANAGE: 'compliance:manage',
  COMPLIANCE_AUDIT: 'compliance:audit',
  INTEGRATIONS_READ: 'integrations:read',
  INTEGRATIONS_CREATE: 'integrations:create',
  INTEGRATIONS_UPDATE: 'integrations:update',
  INTEGRATIONS_DELETE: 'integrations:delete',
  INTEGRATIONS_MANAGE: 'integrations:manage',
  STAFF_CREATE: 'staff:create',
  STAFF_READ: 'staff:read',
  STAFF_UPDATE: 'staff:update',
  STAFF_DELETE: 'staff:delete',
  STAFF_MANAGE: 'staff:manage',
  STAFF_ROLES_MANAGE: 'staff:roles:manage',
  API_KEYS_CREATE: 'api_keys:create',
  API_KEYS_READ: 'api_keys:read',
  API_KEYS_UPDATE: 'api_keys:update',
  API_KEYS_DELETE: 'api_keys:delete',
  API_KEYS_REVOKE: 'api_keys:revoke',
  NOTIFICATIONS_READ: 'notifications:read',
  NOTIFICATIONS_CREATE: 'notifications:create',
  NOTIFICATIONS_MANAGE: 'notifications:manage',
} as const;

export type PermissionType = typeof Permission[keyof typeof Permission];

export const ALL_PERMISSIONS = Object.values(Permission);

export const PERMISSION_GROUPS: Record<PermissionCategory, PermissionType[]> = {
  [PermissionCategory.USERS]: [Permission.USERS_CREATE, Permission.USERS_READ, Permission.USERS_UPDATE, Permission.USERS_DELETE, Permission.USERS_EXPORT, Permission.USERS_APPROVE, Permission.USERS_SUSPEND],
  [PermissionCategory.PATIENTS]: [Permission.PATIENTS_CREATE, Permission.PATIENTS_READ, Permission.PATIENTS_UPDATE, Permission.PATIENTS_DELETE, Permission.PATIENTS_EXPORT, Permission.PATIENTS_ASSIGN, Permission.PATIENTS_ENROLL],
  [PermissionCategory.PROVIDERS]: [Permission.PROVIDERS_CREATE, Permission.PROVIDERS_READ, Permission.PROVIDERS_UPDATE, Permission.PROVIDERS_DELETE, Permission.PROVIDERS_ASSIGN],
  [PermissionCategory.ORGANIZATIONS]: [Permission.ORGANIZATIONS_CREATE, Permission.ORGANIZATIONS_READ, Permission.ORGANIZATIONS_UPDATE, Permission.ORGANIZATIONS_DELETE, Permission.ORGANIZATIONS_MANAGE],
  [PermissionCategory.DEVICES]: [Permission.DEVICES_CREATE, Permission.DEVICES_READ, Permission.DEVICES_UPDATE, Permission.DEVICES_DELETE, Permission.DEVICES_ASSIGN, Permission.DEVICES_ORDER, Permission.DEVICES_SYNC],
  [PermissionCategory.VITALS]: [Permission.VITALS_READ, Permission.VITALS_UPDATE, Permission.VITALS_DELETE, Permission.VITALS_EXPORT],
  [PermissionCategory.BILLING]: [Permission.BILLING_READ, Permission.BILLING_CREATE, Permission.BILLING_UPDATE, Permission.BILLING_DELETE, Permission.BILLING_EXPORT, Permission.BILLING_APPROVE],
  [PermissionCategory.CLAIMS]: [Permission.CLAIMS_READ, Permission.CLAIMS_CREATE, Permission.CLAIMS_UPDATE, Permission.CLAIMS_DELETE, Permission.CLAIMS_SUBMIT, Permission.CLAIMS_APPROVE],
  [PermissionCategory.REPORTS]: [Permission.REPORTS_READ, Permission.REPORTS_CREATE, Permission.REPORTS_EXPORT, Permission.REPORTS_SCHEDULE],
  [PermissionCategory.ANALYTICS]: [Permission.ANALYTICS_READ, Permission.ANALYTICS_EXPORT, Permission.ANALYTICS_ADVANCED],
  [PermissionCategory.SETTINGS]: [Permission.SETTINGS_READ, Permission.SETTINGS_UPDATE, Permission.SETTINGS_MANAGE],
  [PermissionCategory.AUDIT]: [Permission.AUDIT_READ, Permission.AUDIT_EXPORT],
  [PermissionCategory.COMPLIANCE]: [Permission.COMPLIANCE_READ, Permission.COMPLIANCE_MANAGE, Permission.COMPLIANCE_AUDIT],
  [PermissionCategory.INTEGRATIONS]: [Permission.INTEGRATIONS_READ, Permission.INTEGRATIONS_CREATE, Permission.INTEGRATIONS_UPDATE, Permission.INTEGRATIONS_DELETE, Permission.INTEGRATIONS_MANAGE],
  [PermissionCategory.STAFF]: [Permission.STAFF_CREATE, Permission.STAFF_READ, Permission.STAFF_UPDATE, Permission.STAFF_DELETE, Permission.STAFF_MANAGE, Permission.STAFF_ROLES_MANAGE],
  [PermissionCategory.API_KEYS]: [Permission.API_KEYS_CREATE, Permission.API_KEYS_READ, Permission.API_KEYS_UPDATE, Permission.API_KEYS_DELETE, Permission.API_KEYS_REVOKE],
  [PermissionCategory.NOTIFICATIONS]: [Permission.NOTIFICATIONS_READ, Permission.NOTIFICATIONS_CREATE, Permission.NOTIFICATIONS_MANAGE],
};
